[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

# Optional: Redirects for client-side routing (e.g., React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
